apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: gosite

resources:
- ../../clusters/homelab

images:
  - name: gosite
    newName: smarman/gosite
    newTag: 0.0.8
