- op: remove
  path: /spec/rules/0
- op: add
  path: /spec/rules/0
  value:
    host: gosite.local.seanhome.xyz
    http:
      paths:
      - backend:
          serviceName: gosite
          servicePort: http
        path: /