apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
commonLabels:
  env: homelab

resources:
  - namespace.yaml
  - ../../../_charts/argocd-v2.0.4
  - ../../../_charts/argocd-notifications-v1.0.2